name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Stone-Sys
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Argentina/Buenos_Aires
          
          # Personalización Tokyonight (CSS Seguro)
          extras_css: |
            :root {
              --color-canvas-default: #1a1b26;
              --color-fg-default: #a9b1d6;
            }
            .field svg { fill: #7aa2f7; }
            .field { color: #9ece6a; }
            h1, h2, h3 { color: #bb9af7 !important; }
          
          # Plugins para perfil científico
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_sections: most-used
