name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Stone-Sys
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Argentina/Buenos_Aires
          
          # Colores oficiales Tokyonight Storm
          extras_css: |
            :root {
              --color-canvas-default: #1a1b26;    /* Fondo oscuro */
              --color-fg-default: #a9b1d6;        /* Texto gris azulado */
              --color-accent-fg: #7aa2f7;         /* Azul keywords */
            }
            .field svg { fill: #7aa2f7 !important; }
            .field { color: #9ece6a !important; } /* Verde para números */
            h1, h2, h3 { color: #bb9af7 !important; } /* Púrpura para títulos */
            .border { border-color: #414868 !important; } /* Bordes sutiles */

          # Plugins que mencionaste
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_sections: most-used
          
          # Forzamos el modo oscuro para que no use el blanco de GitHub
          config_display: large
